firestarter: fix gcc linking to X11 issue
Fixes this error at compile time due to changes in gcc and/or binutils
packages:
usr/bin/ld: eggtrayicon.o: undefined reference to symbol 'XFlush'
/usr/bin/ld: note: 'XFlush' is defined in DSO /usr/lib/libX11.so.6 so
try adding it to the linker command line
/usr/lib/libX11.so.6: could not read symbols: Invalid operation